# Generated by Django 3.2 on 2023-02-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='Adresse',
            field=models.CharField(default='', max_length=50),
        ),
    ]
