# Generated by Django 3.2 on 2023-02-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Client', models.CharField(default='NomClient', max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Telephone', models.IntegerField(default=0)),
                ('Prix_payer', models.FloatField(default=0)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Matricule', models.CharField(max_length=50)),
                ('Nombre_heurs', models.IntegerField()),
                ('Adresse', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
